#!/usr/bin/env python3
"""Comtains async_comprehension coroutine"""
import asyncio
from typing import List


async def async_comprehension() -> List[float]:
    """Returns the random number generated by async_generator"""
    async_generator = __import__('0-async_generator').async_generator
    result = []
    async for i in async_generator():
        result.append(i)
    return result
